# Home Assistant secrets file
# Replace these placeholder values with your actual sensitive data
# NEVER commit this file to version control with real credentials!

# Location information
latitude: 37.7749
longitude: -122.4194
elevation: 30
time_zone: America/Los_Angeles

# MQTT broker credentials
mqtt_broker_host: 192.168.1.100
mqtt_broker_port: 1883
mqtt_username: mqtt_user
mqtt_password: mqtt_password

# Credentials for other services, if needed
# database_url: postgresql://username:password@localhost/database_name